In [ ]:
!pip install numpy==1.23.5 gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 2.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 51.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 48.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 13.4 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.3
    Uninstalling scipy-1.15.3:
      Successfully uninstalled scipy-1.15.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jaxlib 0.5.1 requires numpy>=1.25, but you have numpy 1.23.5 which is incompatible.
jax 0.5.2 requires numpy>=1.25, but you have numpy 1.23.5 which is incompatible.
xarray 2025.3.1 requires numpy>=1.24, but yo

In [ ]:
import io

# Read the corpus line by line
def load_corpus(fname):
    fin = io.open(fname, 'r', encoding='utf-8', newline='\n', errors='ignore')
    texts = []
    for line in fin:
        texts.append(line.split())
    return texts

In [ ]:
corpus = load_corpus('filtered_slovenian_corpus.txt')

The corpus contains 4323 texts

In [ ]:
len(corpus)

4323

In [ ]:
corpus[0]

['odlomek',
 'iz',
 'sanja',
 'vožnja',
 'biti',
 'tih',
 'negibnost',
 'negiben',
 'zvenenje',
 'sluten',
 'noben',
 'pričakovanje',
 'ozračje',
 'biti',
 'gost',
 'zavešen',
 'z',
 'opečnat',
 'bel',
 'emajliran',
 'ploščad',
 'drseti',
 'po',
 'prostor',
 'number1',
 'tog',
 'postava',
 'number1',
 'obraz',
 'razvrščen',
 'v',
 'krog',
 'dekle',
 'in',
 'number1',
 'fant',
 'v',
 'moten',
 'veter',
 'na',
 'pot',
 'iz',
 'tema',
 'oči',
 'ves',
 'biti',
 'uprt',
 'v',
 'ves',
 'oči',
 'ves',
 'biti',
 'slep',
 'le',
 'še',
 'bled',
 'svetlikanje',
 'za',
 'person1',
 'oster',
 'pločevina',
 'zamolkel',
 'lesk',
 'rob',
 'parati',
 'prostor',
 'lesk',
 'biti',
 'podoben',
 'zvok',
 'biti',
 'čisto',
 'na',
 'rob',
 'med',
 'mrtvilo',
 'in',
 'sproščanje',
 'zazveneti',
 'biti',
 'zazveneti',
 'biti',
 'zazveneti',
 'zazveneti',
 'obraz',
 'fant',
 'pokrivati',
 'rumen',
 'puder',
 'rumen',
 'zelo',
 'rumen',
 'hladno',
 'rumen',
 'ustnica',
 'biti',
 'in',
 'gladek',
 'kot',
 'ribji'

Model configs:
- *vector_size*: 100 (default)
- *window*: 5 (default)
- *min_count*: 1, 5, 10 (default)
- *workers*: 3 (default)
- *sg*: CBOW  (default)
- *hs*: negative sampling (default)
- *negative*: negative sampling, 5 (default)
- *max_vocab_size*: None (default)
- *epochs*: 5 (default)



In [ ]:
%%time
from gensim.models import Word2Vec

dimension = 100
model = Word2Vec(sentences=corpus, vector_size=dimension, min_count=1)

CPU times: user 11min 42s, sys: 3.95 s, total: 11min 46s
Wall time: 7min 48s


In [ ]:
dictionary = {key : model.wv[key] for key in model.wv.key_to_index}

In [ ]:
# Unique words in the dictionary
len(dictionary)

245693

In [ ]:
%%time
from gensim.models import Word2Vec

dimension = 100
model5 = Word2Vec(sentences=corpus, vector_size=dimension, min_count=5)

CPU times: user 9min 26s, sys: 2.78 s, total: 9min 29s
Wall time: 5min 53s


In [ ]:
dictionary5 = {key : model5.wv[key] for key in model5.wv.key_to_index}

In [ ]:
len(dictionary5)

186405

In [ ]:
%%time
from gensim.models import Word2Vec

dimension = 100
model10 = Word2Vec(sentences=corpus, vector_size=dimension, min_count=10)

CPU times: user 10min 59s, sys: 3.02 s, total: 11min 2s
Wall time: 7min 11s


In [ ]:
dictionary10 = {key : model10.wv[key] for key in model10.wv.key_to_index}

In [ ]:
len(dictionary10)

122442

In [ ]:
%%time
model102 = Word2Vec(sentences=corpus, vector_size=dimension, window=10,
    min_count=10,
    workers=5,
    epochs=10)

CPU times: user 24min 27s, sys: 6.02 s, total: 24min 33s
Wall time: 15min


In [ ]:
dictionary102 = {key : model102.wv[key] for key in model102.wv.key_to_index}

In [ ]:
len(dictionary102)

122442

# Cosine similarity

Test the embeddings using the cosine distance to find the closest word

In [ ]:
model.wv.most_similar('ljubezen') # любовь

[('ljubezin', 0.7443608641624451),
 ('hvaležnost', 0.7351136207580566),
 ('vdanost', 0.7278461456298828),
 ('ljubav', 0.7186066508293152),
 ('ljubeznija', 0.6911452412605286),
 ('lju', 0.6844321489334106),
 ('sočutje', 0.6788191199302673),
 ('usmiljenost', 0.6761879324913025),
 ('prijateljstvo', 0.649135410785675),
 ('spoštovanje', 0.6480661034584045)]

In [ ]:
model5.wv.most_similar('ljubezen')

[('ljubezin', 0.7343877553939819),
 ('hvaležnost', 0.7269481420516968),
 ('vdanost', 0.7230265140533447),
 ('lju', 0.6998092532157898),
 ('ljubav', 0.6946496963500977),
 ('sočutje', 0.6898185610771179),
 ('ljubeznija', 0.6815904974937439),
 ('usmiljenost', 0.6663395762443542),
 ('spoštovanje', 0.6516414880752563),
 ('zvestost', 0.6395222544670105)]

In [ ]:
model10.wv.most_similar('ljubezen')

[('ljubezin', 0.775059700012207),
 ('hvaležnost', 0.7430786490440369),
 ('vdanost', 0.7302815318107605),
 ('lju', 0.7154040932655334),
 ('ljubeznija', 0.7108976244926453),
 ('ljubav', 0.6898540258407593),
 ('usmiljenost', 0.680066704750061),
 ('sočutje', 0.6710894703865051),
 ('milosrčnost', 0.658089816570282),
 ('udanost', 0.6555747985839844)]

In [ ]:
model.wv.most_similar('noč') # ночь

[('noh', 0.6933416724205017),
 ('večer', 0.6613051891326904),
 ('mrak', 0.6402956247329712),
 ('noha', 0.6232649683952332),
 ('noc', 0.6083472967147827),
 ('ponoči', 0.5921524167060852),
 ('jutro', 0.575903594493866),
 ('zima', 0.5695030093193054),
 ('polnoč', 0.5513136982917786),
 ('popoldan', 0.5385251641273499)]

In [ ]:
model5.wv.most_similar('noč')

[('noh', 0.700498104095459),
 ('mrak', 0.6718565821647644),
 ('noc', 0.6508113741874695),
 ('večer', 0.6409862041473389),
 ('noha', 0.6337021589279175),
 ('ponoči', 0.5763673186302185),
 ('zima', 0.570056676864624),
 ('jutro', 0.5688253045082092),
 ('polnoč', 0.5457406044006348),
 ('popoldan', 0.5439216494560242)]

In [ ]:
model10.wv.most_similar('noč')

[('noh', 0.6645951271057129),
 ('mrak', 0.6488473415374756),
 ('večer', 0.6268515586853027),
 ('noha', 0.615777313709259),
 ('ponoči', 0.5896427035331726),
 ('noc', 0.5839037299156189),
 ('popoldan', 0.5513639450073242),
 ('zima', 0.5502399802207947),
 ('jutro', 0.5480504035949707),
 ('dana', 0.5275076627731323)]

In [ ]:
model.wv.most_similar('bolnišnica') # больница

[('bolnica', 0.8452498912811279),
 ('blaznica', 0.7808130383491516),
 ('hiralnica', 0.7784332036972046),
 ('sirotišnica', 0.728280246257782),
 ('norišnica', 0.7279091477394104),
 ('zavod', 0.6862524151802063),
 ('ubožnica', 0.6470041871070862),
 ('lekarna', 0.6359512805938721),
 ('kaznilnica', 0.6288341283798218),
 ('špital', 0.6203216314315796)]

In [ ]:
model5.wv.most_similar('bolnišnica')

[('bolnica', 0.8536751866340637),
 ('hiralnica', 0.7626286149024963),
 ('blaznica', 0.7325839400291443),
 ('sirotišnica', 0.7120245695114136),
 ('norišnica', 0.7018075585365295),
 ('zavod', 0.6997953653335571),
 ('oskrbovališče', 0.6687705516815186),
 ('bolniški', 0.6502309441566467),
 ('ubožnica', 0.645808756351471),
 ('bolniščnica', 0.6425885558128357)]

In [ ]:
model10.wv.most_similar('bolnišnica')

[('bolnica', 0.8429074287414551),
 ('blaznica', 0.7511019706726074),
 ('hiralnica', 0.7476999163627625),
 ('zavod', 0.6909267902374268),
 ('sirotišnica', 0.6862621307373047),
 ('ubožnica', 0.6704066395759583),
 ('lekarna', 0.6632823944091797),
 ('norišnica', 0.660028874874115),
 ('jetnišnica', 0.6264970302581787),
 ('bolniščnica', 0.6208772659301758)]

In [ ]:
model.wv.most_similar('vrata') # дверь

[('duri', 0.9040144085884094),
 ('dur', 0.8448166847229004),
 ('dveri', 0.7953341007232666),
 ('dura', 0.7808150053024292),
 ('vratca', 0.7772207260131836),
 ('duriti', 0.7752901315689087),
 ('dver', 0.7672568559646606),
 ('vratič', 0.7491240501403809),
 ('okno', 0.7328328490257263),
 ('okence', 0.7184924483299255)]

In [ ]:
model5.wv.most_similar('vrata')

[('duri', 0.9047405123710632),
 ('dur', 0.8611709475517273),
 ('dveri', 0.788261890411377),
 ('vratca', 0.7764025926589966),
 ('dura', 0.7665100693702698),
 ('okno', 0.7519477009773254),
 ('dver', 0.7442157864570618),
 ('duriti', 0.7394031286239624),
 ('vratič', 0.7384836077690125),
 ('okence', 0.7217069864273071)]

In [ ]:
model10.wv.most_similar('vrata')

[('duri', 0.9138798713684082),
 ('dur', 0.8554231524467468),
 ('dveri', 0.8037192225456238),
 ('dver', 0.7908201813697815),
 ('vratca', 0.787938117980957),
 ('dura', 0.7801281809806824),
 ('vratič', 0.7721148729324341),
 ('duriti', 0.7523799538612366),
 ('ključavnica', 0.7429252862930298),
 ('okno', 0.7388753890991211)]

In [ ]:
# Should return "kraljica" (queen)
model5.wv.most_similar(positive=["žena", "kralj"], negative=["moški"])

[('vojvoda', 0.6235020756721497),
 ('car', 0.6080947518348694),
 ('cesar', 0.6029267907142639),
 ('sultan', 0.602124810218811),
 ('kraljevič', 0.5961639881134033),
 ('ohet', 0.5921636819839478),
 ('knez', 0.5845325589179993),
 ('kraljica', 0.5749280452728271),
 ('princesinja', 0.5737755298614502),
 ('kraljičen', 0.5716594457626343)]

In [ ]:
model10.wv.most_similar(positive=["žena", "kralj"], negative=["moški"])

[('vojvoda', 0.6240739822387695),
 ('ohet', 0.6114301085472107),
 ('car', 0.6105125546455383),
 ('kraljevič', 0.6057676076889038),
 ('kraljica', 0.5911204814910889),
 ('cesar', 0.5906939506530762),
 ('oče', 0.5888693928718567),
 ('sultan', 0.5805400609970093),
 ('sina', 0.5667123198509216),
 ('knez', 0.5665797591209412)]

# Save the dictionary

In [ ]:
# Save to the file
def save_dictionary(fname, dictionary, args):
    length, dimension = args
    fin = io.open(fname, 'w', encoding='utf-8')
    fin.write('%d %d\n' % (length, dimension))
    for word in dictionary:
        fin.write('%s %s\n' % (word, ' '.join(map(str, dictionary[word]))))

# Load from the file
def load_dictionary(fname):
    fin = io.open(fname, 'r', encoding='utf-8', newline='\n', errors='ignore')
    length, dimension = map(int, fin.readline().split())
    dictionary = {}
    for line in fin:
        tokens = line.rstrip().split(' ')
        dictionary[tokens[0]] = map(float, tokens[1:])
    return dictionary

In [ ]:
# Save the dictionary
save_dictionary('slovenian_lit_cbow_dictionary.txt', dictionary102, (len(dictionary102), dimension))

In [ ]:
# Check that everything is saved correctly
loaded_dictionary = load_dictionary('slovenian_lit_cbow_dictionary.txt')
len(dictionary102) == len(loaded_dictionary)

True

# Normalize embeddings

In [ ]:
import numpy as np

# Only vectors
embeddings = np.array([model102.wv[key] for key in model102.wv.key_to_index])

In [ ]:
if isinstance(dictionary102, dict):
    embeddings_array = np.stack(list(dictionary102.values()))
    print(embeddings_array.shape)

(122442, 100)


In [ ]:
# To be safe
embeddings == embeddings_array

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [ ]:
print(np.mean(embeddings, axis=0))

[-0.07059771  0.03941076  0.10930424  0.15353803  0.05931872 -0.10170517
  0.04471296  0.24379937 -0.0657516  -0.14199336 -0.04182344 -0.14766984
 -0.16159578  0.05366978  0.11611334 -0.03227548  0.08187168 -0.10060285
  0.04742604 -0.12660177  0.03224041  0.15476266  0.16851442 -0.06496949
  0.03872925 -0.05034385 -0.05031683 -0.0078432  -0.08056895  0.08916444
  0.07734482 -0.10094862 -0.05585996 -0.11030429 -0.13264331  0.03822085
  0.07008892 -0.03164747 -0.02296917 -0.0578387   0.07054667 -0.09232847
 -0.04766405  0.0231702   0.08084486 -0.02830119 -0.12071595  0.12438279
  0.06324868  0.02113148  0.0470047  -0.05839137 -0.01198034  0.03716147
 -0.06762396  0.07516376  0.11207464  0.00672192 -0.0158732   0.00782592
  0.09230177  0.13044569 -0.03177659  0.0031035  -0.04523661  0.05158734
 -0.10364844  0.14823744 -0.0212756   0.09645062  0.00652571  0.12034094
  0.25995535 -0.10706577  0.02700309  0.02520932 -0.02806316 -0.06674539
 -0.00265587 -0.06297791 -0.13943194  0.01062474  0

In [ ]:
# Count length of every vector
lengths = np.linalg.norm(embeddings, axis=1)

print("Min:", np.min(lengths))
print("Max:", np.max(lengths))
print("Mean:", np.mean(lengths))

tolerance = 1e-6
is_normalized = np.allclose(lengths, 1.0, atol=tolerance)
print("Normalized?", is_normalized)

Min: 0.048922785
Max: 38.42067
Mean: 4.100624
Normalized? False


In [ ]:
normalized_embeddings = embeddings / np.linalg.norm(embeddings, axis=1, keepdims=True)

np.linalg.norm(normalized_embeddings[0]) # 1.0 if normalized

1.0

In [ ]:
lengths = np.linalg.norm(normalized_embeddings, axis=1)
print("Min:", np.min(lengths), "Max:", np.max(lengths))

Min: 0.99999976 Max: 1.0000001


In [ ]:
embeddings.shape, normalized_embeddings.shape

((122442, 100), (122442, 100))

In [ ]:
# Save the vectors
np.save('slv_cbow_embeddings.npy', embeddings)
np.save('slv_cbow_norm_embeddings.npy', normalized_embeddings)

In [ ]:
normalized_embeddings[0]

array([ 0.02118168,  0.05342397, -0.14375383, -0.02004769, -0.00900114,
       -0.14250864, -0.03068894,  0.02022715,  0.23298879,  0.1512992 ,
        0.12434006,  0.15572858, -0.09069086,  0.09044349,  0.06240951,
        0.00926695, -0.11652884,  0.06036509,  0.1272649 , -0.15125626,
        0.02916634, -0.2109348 , -0.10176457,  0.08630629, -0.03008753,
       -0.09506394,  0.16431053, -0.06911016, -0.03953129, -0.04611079,
        0.01551666,  0.07337324, -0.00821816,  0.14733693,  0.0081516 ,
        0.10107444, -0.08414944,  0.04110866, -0.19735086, -0.05783328,
       -0.29834217,  0.15377979, -0.02088827,  0.06053209, -0.07876908,
        0.12414975,  0.06215041, -0.01024656, -0.07889498, -0.03305475,
        0.05111475,  0.03049413, -0.01741393, -0.01334824, -0.0184912 ,
        0.12769285, -0.16424446, -0.02933215, -0.0625499 , -0.08111831,
        0.07617046,  0.03291896,  0.0443411 , -0.0536753 , -0.10379271,
       -0.08132328, -0.03250827, -0.06878819,  0.04599227, -0.17

In [ ]:
keys = list(dictionary102.keys())

embeddings_dict = {keys[i]: embeddings[i] for i in range(len(keys))}
norm_embeddings_dict = {keys[i]: normalized_embeddings[i] for i in range(len(keys))}

len(embeddings_dict), len(norm_embeddings_dict)

(122442, 122442)

In [ ]:
# Save the words+vectors
np.save("slv_cbow_dictionary.npy", embeddings_dict)
np.save("slv_cbow_norm_dictionary.npy", norm_embeddings_dict)

In [ ]:
list(embeddings_dict.items())[:5]

[('biti',
  array([ 2.245511  , -0.37591004,  0.07359289, -0.86844724, -1.2867113 ,
         -0.53872   , -0.35111532, -0.91323733,  0.85150135,  1.6219636 ,
         -0.08780624,  2.120182  ,  1.1496775 ,  1.0370028 , -0.5263339 ,
          1.0130963 , -1.7144357 ,  0.34298754, -0.67178935,  1.6849141 ,
          0.3686291 , -0.76096517, -0.6851049 ,  1.5850188 ,  0.92904323,
         -1.2029287 ,  0.48766077,  0.22314648,  0.7467015 , -1.4872613 ,
         -0.4462796 ,  0.20368767,  0.8325704 ,  0.17927776, -0.41679892,
          0.38266817,  1.3205478 , -0.5426678 ,  0.65719974,  0.3909346 ,
         -0.41382942, -0.51402354,  0.5346958 ,  0.04475643, -1.1537037 ,
          1.9535066 , -0.565452  ,  1.2258329 , -0.22880074, -0.9885923 ,
          1.164527  , -0.60965526, -1.5852169 ,  0.6375975 , -0.42674032,
          0.7400644 , -2.1717079 , -0.27081555, -0.80371976, -0.8869421 ,
         -0.44763824,  1.2604892 , -0.8626594 , -1.4548442 ,  0.09213062,
         -0.51633334, -0.271

In [ ]:
list(norm_embeddings_dict.items())[:5]

[('biti',
  array([ 0.22443342, -0.0375713 ,  0.00735543, -0.08679921, -0.1286037 ,
         -0.05384377, -0.03509313, -0.09127588,  0.08510551,  0.16211136,
         -0.00877602,  0.21190709,  0.1149075 ,  0.10364594, -0.05260581,
          0.10125654, -0.17135373,  0.03428078, -0.06714373,  0.16840312,
          0.03684359, -0.07605664, -0.06847459,  0.1584188 ,  0.09285564,
         -0.12022983,  0.04874052,  0.02230295,  0.07463101, -0.14864819,
         -0.04460457,  0.02035809,  0.0832134 ,  0.01791838, -0.04165805,
          0.03824676,  0.13198557, -0.05423834,  0.06568553,  0.03907297,
         -0.04136125, -0.05137542,  0.05344156,  0.0044733 , -0.11530991,
          0.19524829, -0.05651557,  0.12251905, -0.02286808, -0.09880742,
          0.11639168, -0.06093358, -0.15843861,  0.06372634, -0.04265167,
          0.07396766, -0.21705697, -0.02706736, -0.08032986, -0.08864773,
         -0.04474036,  0.12598287, -0.08622073, -0.14540818,  0.00920823,
         -0.05160628, -0.027

In [ ]:
list(dictionary5.items())[:5]

[('biti',
  array([ 2.245511  , -0.37591004,  0.07359289, -0.86844724, -1.2867113 ,
         -0.53872   , -0.35111532, -0.91323733,  0.85150135,  1.6219636 ,
         -0.08780624,  2.120182  ,  1.1496775 ,  1.0370028 , -0.5263339 ,
          1.0130963 , -1.7144357 ,  0.34298754, -0.67178935,  1.6849141 ,
          0.3686291 , -0.76096517, -0.6851049 ,  1.5850188 ,  0.92904323,
         -1.2029287 ,  0.48766077,  0.22314648,  0.7467015 , -1.4872613 ,
         -0.4462796 ,  0.20368767,  0.8325704 ,  0.17927776, -0.41679892,
          0.38266817,  1.3205478 , -0.5426678 ,  0.65719974,  0.3909346 ,
         -0.41382942, -0.51402354,  0.5346958 ,  0.04475643, -1.1537037 ,
          1.9535066 , -0.565452  ,  1.2258329 , -0.22880074, -0.9885923 ,
          1.164527  , -0.60965526, -1.5852169 ,  0.6375975 , -0.42674032,
          0.7400644 , -2.1717079 , -0.27081555, -0.80371976, -0.8869421 ,
         -0.44763824,  1.2604892 , -0.8626594 , -1.4548442 ,  0.09213062,
         -0.51633334, -0.271

# FastText

Download the pretrained model for Slovenian based on Wikipedia articles

In [ ]:
!pip install fasttext

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.4/73.4 kB 2.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached pybind11-2.13.6-py3-none-any.whl.metadata (9.5 kB)
Using cached pybind11-2.13.6-py3-none-any.whl (243 kB)
  Created wheel for fasttext: filename=fasttext-0.9.3-cp311-cp311-linux_x86_64.whl size=4313505 sha256=9a06539a17b555d65a9c0c71d72e6c1c19291490b45c13e7ea3a449629f7155e
  Stored in directory: /root/.cache/pip/wheels/65/4f/35/5057db0249224e9ab55a513fa6b79451473ceb7713017823c3
Successfully built fasttext


In [ ]:
import fasttext.util

# fasttext.util.download_model('sl', if_exists='ignore')
fasttext_model = fasttext.util.download_model('sl', if_exists='ignore')

In [ ]:
fasttext_model = fasttext.load_model('cc.sl.300.bin.gz.part')

ValueError: cc.sl.300.bin.gz.part has wrong file format!

In [ ]:
fasttext_model.get_dimension()

In [ ]:
# Reduce the dimension of the vectors
required_dimension = 100
fasttext.util.reduce_model(fasttext_model, required_dimension)
fasttext_model.get_dimension()

In [ ]:
fasttext_dictionary = {key : model.get_word_vector(key) for key in model.get_words()}

In [ ]:
len(fasttext_dictionary)

In [ ]:
save_dictionary('slv_fasttext_dictionary.txt', dictionary, (len(dictionary), model.get_dimension()))